### ISSUE TITLE
bash: ./configure: No such file or directory error 

### ISSUE THREAD

**Issue by gideion** [hadess/iio-sensor-proxy#209] opened 2018-01-10 05:41 UTC
When attempting  ~/Git/iio-sensor-proxy$ ./configure --prefix=/usr --sysconfdir=/etc
I get the error 
bash: ./configure: No such file or directory

Running Ubuntu 16.04

thx

**Comment by hadess** [comment] 2018-01-10 12:25
Use your distribution's packages, or use tarballs to  build iio-sensor-proxy.
Duplicate of #149

**Closed by hadess** 2018-01-10 12:25 UTC
Labels: invalid, question
