### ISSUE TITLE
Orientation: Undefined on X1 Yoga (G3) Antergos (Arch based)

### ISSUE THREAD

**Issue by edhilgendorf** [hadess/iio-sensor-proxy#273] opened 2019-05-20 00:05 UTC
system
------------------------------------------------------------------
5.1.2-arch1-1-ARCH (Antergos) on X1 Yoga (G3)

monitor-sensor
------------------------------------------------------------------
   Waiting for iio-sensor-proxy to appear
+++ iio-sensor-proxy appeared
=== Has accelerometer (orientation: undefined)
=== Has ambient light sensor (value: 0.000000, unit: lux)

iio-sensor-proxy status
------------------------------------------------------------------
● iio-sensor-proxy.service - IIO Sensor Proxy service
   Loaded: loaded (/usr/lib/systemd/system/iio-sensor-proxy.service; static; vendor preset: disabled)
   Active: active (running) since Sun 2019-05-19 15:26:15 PDT; 1h 35min ago
 Main PID: 680 (iio-sensor-prox)
    Tasks: 3 (limit: 4915)
   Memory: 1.9M
   CGroup: /system.slice/iio-sensor-proxy.service
           └─680 /usr/bin/iio-sensor-proxy

May 19 15:26:15 fireside systemd[1]: Starting IIO Sensor Proxy service...
May 19 15:26:15 fireside systemd[1]: Started IIO Sensor Proxy service.
May 19 15:29:04 fireside systemd[1]: iio-sensor-proxy.service: Current command vanished from the unit file, execution of the command list won't be resumed.

**Comment by edhilgendorf** [comment] 2019-05-20 00:09
Debug
`** (process:29051): DEBUG: 17:07:50.073: Found IIO buffer ALS at /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0001/HID-SENSOR-200041.3.auto/iio:device1
** (process:29051): DEBUG: 17:07:50.075: Found device /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0001/HID-SENSOR-200041.3.auto/iio:device1 of type ambient light sensor at IIO Buffer Light sensor
** (process:29051): DEBUG: 17:07:50.076: Found associated trigger at /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/trigger0
** (process:29051): DEBUG: 17:07:50.076: Found IIO buffer accelerometer at /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0
** (process:29051): DEBUG: 17:07:50.076: No autodetected location, falling back to display location
** (process:29051): DEBUG: 17:07:50.076: Found device /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0 of type accelerometer at IIO Buffer accelerometer
** (process:29051): DEBUG: 17:07:50.081: Found associated trigger at /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/trigger0
** (process:29051): DEBUG: 17:07:50.082: Already enabled sensor /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0/scan_elements/in_accel_x_en
** (process:29051): DEBUG: 17:07:50.082: Already enabled sensor /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0/scan_elements/in_accel_z_en
** (process:29051): DEBUG: 17:07:50.082: Already enabled sensor /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0/scan_elements/in_timestamp_en
** (process:29051): DEBUG: 17:07:50.082: Already enabled sensor /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0/scan_elements/in_accel_y_en
** (process:29051): DEBUG: 17:07:50.082: Trying to read 'in_accel_x_scale' (name) from dir '/sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0'
** (process:29051): DEBUG: 17:07:50.083: Failed to read float from /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0/in_accel_x_scale: No such file or directory
** (process:29051): DEBUG: 17:07:50.083: Trying to read 'in_accel_scale' (generic name) from dir '/sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0'
** (process:29051): DEBUG: 17:07:50.083: Trying to read 'in_accel_x_offset' (name) from dir '/sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0'
** (process:29051): DEBUG: 17:07:50.083: Failed to read float from /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0/in_accel_x_offset: No such file or directory
** (process:29051): DEBUG: 17:07:50.083: Trying to read 'in_accel_offset' (generic name) from dir '/sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0'
** (process:29051): DEBUG: 17:07:50.083: Got type for in_accel_x: is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:29051): DEBUG: 17:07:50.083: Trying to read 'in_accel_z_scale' (name) from dir '/sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0'
** (process:29051): DEBUG: 17:07:50.083: Failed to read float from /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0/in_accel_z_scale: No such file or directory
** (process:29051): DEBUG: 17:07:50.083: Trying to read 'in_accel_scale' (generic name) from dir '/sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0'
** (process:29051): DEBUG: 17:07:50.083: Trying to read 'in_accel_z_offset' (name) from dir '/sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0'
** (process:29051): DEBUG: 17:07:50.083: Failed to read float from /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0/in_accel_z_offset: No such file or directory
** (process:29051): DEBUG: 17:07:50.083: Trying to read 'in_accel_offset' (generic name) from dir '/sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0'
** (process:29051): DEBUG: 17:07:50.083: Got type for in_accel_z: is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:29051): DEBUG: 17:07:50.083: Trying to read 'in_timestamp_scale' (name) from dir '/sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0'
** (process:29051): DEBUG: 17:07:50.083: Failed to read float from /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0/in_timestamp_scale: No such file or directory
** (process:29051): DEBUG: 17:07:50.083: Trying to read 'in_scale' (generic name) from dir '/sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0'
** (process:29051): DEBUG: 17:07:50.083: Failed to read float from /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0/in_scale: No such file or directory
** (process:29051): DEBUG: 17:07:50.083: Trying to read 'in_timestamp_offset' (name) from dir '/sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0'
** (process:29051): DEBUG: 17:07:50.083: Failed to read float from /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0/in_timestamp_offset: No such file or directory
** (process:29051): DEBUG: 17:07:50.083: Trying to read 'in_offset' (generic name) from dir '/sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0'
** (process:29051): DEBUG: 17:07:50.083: Failed to read float from /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0/in_offset: No such file or directory
** (process:29051): DEBUG: 17:07:50.083: Got type for in_timestamp: is signed: 1, bytes: 8, bits_used: 64, shift: 0, mask: 0x18446744073709551615, be: 0
** (process:29051): DEBUG: 17:07:50.083: Trying to read 'in_accel_y_scale' (name) from dir '/sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0'
** (process:29051): DEBUG: 17:07:50.083: Failed to read float from /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0/in_accel_y_scale: No such file or directory
** (process:29051): DEBUG: 17:07:50.083: Trying to read 'in_accel_scale' (generic name) from dir '/sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0'
** (process:29051): DEBUG: 17:07:50.083: Trying to read 'in_accel_y_offset' (name) from dir '/sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0'
** (process:29051): DEBUG: 17:07:50.083: Failed to read float from /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0/in_accel_y_offset: No such file or directory
** (process:29051): DEBUG: 17:07:50.083: Trying to read 'in_accel_offset' (generic name) from dir '/sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0002/HID-SENSOR-200073.14.auto/iio:device0'
** (process:29051): DEBUG: 17:07:50.083: Got type for in_accel_y: is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:29051): DEBUG: 17:07:50.083: Built channel array for in_accel_x: index: 0, is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:29051): DEBUG: 17:07:50.083: Built channel array for in_accel_y: index: 1, is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:29051): DEBUG: 17:07:50.083: Built channel array for in_accel_z: index: 2, is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:29051): DEBUG: 17:07:50.083: Built channel array for in_timestamp: index: 3, is signed: 1, bytes: 8, bits_used: 64, shift: 0, mask: 0x18446744073709551615, be: 0
** (process:29051): DEBUG: 17:07:50.083: Failed to auto-detect mount matrix, falling back to identity
** (process:29051): DEBUG: 17:07:50.083: No autodetected location, falling back to display location
** (process:29051): DEBUG: 17:07:50.084: Found associated trigger at /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0001/HID-SENSOR-200041.3.auto/trigger1
** (process:29051): DEBUG: 17:07:50.085: Already enabled sensor /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0001/HID-SENSOR-200041.3.auto/iio:device1/scan_elements/in_intensity_both_en
** (process:29051): DEBUG: 17:07:50.085: Already enabled sensor /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0001/HID-SENSOR-200041.3.auto/iio:device1/scan_elements/in_illuminance_en
** (process:29051): DEBUG: 17:07:50.085: Trying to read 'in_intensity_both_scale' (name) from dir '/sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0001/HID-SENSOR-200041.3.auto/iio:device1'
** (process:29051): DEBUG: 17:07:50.085: Failed to read float from /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0001/HID-SENSOR-200041.3.auto/iio:device1/in_intensity_both_scale: No such file or directory
** (process:29051): DEBUG: 17:07:50.085: Trying to read 'in_intensity_scale' (generic name) from dir '/sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0001/HID-SENSOR-200041.3.auto/iio:device1'
** (process:29051): DEBUG: 17:07:50.086: Trying to read 'in_intensity_both_offset' (name) from dir '/sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0001/HID-SENSOR-200041.3.auto/iio:device1'
** (process:29051): DEBUG: 17:07:50.086: Failed to read float from /sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0001/HID-SENSOR-200041.3.auto/iio:device1/in_intensity_both_offset: No such file or directory
** (process:29051): DEBUG: 17:07:50.086: Trying to read 'in_intensity_offset' (generic name) from dir '/sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0001/HID-SENSOR-200041.3.auto/iio:device1'
** (process:29051): DEBUG: 17:07:50.086: Got type for in_intensity_both: is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:29051): DEBUG: 17:07:50.086: Trying to read 'in_illuminance_scale' (name) from dir '/sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0001/HID-SENSOR-200041.3.auto/iio:device1'
** (process:29051): DEBUG: 17:07:50.086: Trying to read 'in_illuminance_offset' (name) from dir '/sys/devices/pci0000:00/0000:00:13.0/{33AECD58-B679-4E54-9BD9-A04D34F0C226}/001F:8087:0AC2.0001/HID-SENSOR-200041.3.auto/iio:device1'
** (process:29051): DEBUG: 17:07:50.086: Got type for in_illuminance: is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:29051): DEBUG: 17:07:50.086: Built channel array for in_intensity_both: index: 0, is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:29051): DEBUG: 17:07:50.086: Built channel array for in_illuminance: index: 1, is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:29051): DEBUG: 17:07:50.087: Handling driver refcounting method 'ClaimLight' for ambient light sensor device
** (process:29051): DEBUG: 17:07:50.087: Handling driver refcounting method 'ClaimAccelerometer' for accelerometer device
** (process:29051): DEBUG: 17:07:50.788: No new data available on 'iio:device1'
** (process:29051): DEBUG: 17:07:50.788: process_scan_1: channel_index: 0, chan_name: in_accel_x, channel_data_index: 0 location: 0 bytes: 4 is_signed: 1 be: 0 shift: 0 bits_used: 32
** (process:29051): DEBUG: 17:07:50.788: process_scan_1: channel_index: 1, chan_name: in_accel_y, channel_data_index: 1 location: 4 bytes: 4 is_signed: 1 be: 0 shift: 0 bits_used: 32
** (process:29051): DEBUG: 17:07:50.788: process_scan_1: channel_index: 2, chan_name: in_accel_z, channel_data_index: 2 location: 8 bytes: 4 is_signed: 1 be: 0 shift: 0 bits_used: 32
** (process:29051): DEBUG: 17:07:50.788: Accel read from IIO on 'iio:device0': 0, 0, 0 (scale 0.000010)
** (process:29051): DEBUG: 17:07:50.788: Accel sent by driver (quirk applied): 0, 0, 0 (scale: 0.000010)
** (process:29051): DEBUG: 17:07:51.489: No new data available on 'iio:device1'
** (process:29051): DEBUG: 17:07:51.489: process_scan_1: channel_index: 0, chan_name: in_accel_x, channel_data_index: 0 location: 0 bytes: 4 is_signed: 1 be: 0 shift: 0 bits_used: 32
** (process:29051): DEBUG: 17:07:51.489: process_scan_1: channel_index: 1, chan_name: in_accel_y, channel_data_index: 1 location: 4 bytes: 4 is_signed: 1 be: 0 shift: 0 bits_used: 32
** (process:29051): DEBUG: 17:07:51.490: process_scan_1: channel_index: 2, chan_name: in_accel_z, channel_data_index: 2 location: 8 bytes: 4 is_signed: 1 be: 0 shift: 0 bits_used: 32
** (process:29051): DEBUG: 17:07:51.490: Accel read from IIO on 'iio:device0': 0, 0, 0 (scale 0.000010)
** (process:29051): DEBUG: 17:07:51.490: Accel sent by driver (quirk applied): 0, 0, 0 (scale: 0.000010)
** (process:29051): DEBUG: 17:07:52.191: No new data available on 'iio:device1'
** (process:29051): DEBUG: 17:07:52.191: process_scan_1: channel_index: 0, chan_name: in_accel_x, channel_data_index: 0 location: 0 bytes: 4 is_signed: 1 be: 0 shift: 0 bits_used: 32
** (process:29051): DEBUG: 17:07:52.191: process_scan_1: channel_index: 1, chan_name: in_accel_y, channel_data_index: 1 location: 4 bytes: 4 is_signed: 1 be: 0 shift: 0 bits_used: 32
** (process:29051): DEBUG: 17:07:52.191: process_scan_1: channel_index: 2, chan_name: in_accel_z, channel_data_index: 2 location: 8 bytes: 4 is_signed: 1 be: 0 shift: 0 bits_used: 32
** (process:29051): DEBUG: 17:07:52.191: Accel read from IIO on 'iio:device0': 0, 0, 0 (scale 0.000010)
** (process:29051): DEBUG: 17:07:52.191: Accel sent by driver (quirk applied): 0, 0, 0 (scale: 0.000010)
** (process:29051): DEBUG: 17:07:52.892: No new data available on 'iio:device1'
** (process:29051): DEBUG: 17:07:52.892: process_scan_1: channel_index: 0, chan_name: in_accel_x, channel_data_index: 0 location: 0 bytes: 4 is_signed: 1 be: 0 shift: 0 bits_used: 32
** (process:29051): DEBUG: 17:07:52.892: process_scan_1: channel_index: 1, chan_name: in_accel_y, channel_data_index: 1 location: 4 bytes: 4 is_signed: 1 be: 0 shift: 0 bits_used: 32
** (process:29051): DEBUG: 17:07:52.892: process_scan_1: channel_index: 2, chan_name: in_accel_z, channel_data_index: 2 location: 8 bytes: 4 is_signed: 1 be: 0 shift: 0 bits_used: 32
** (process:29051): DEBUG: 17:07:52.892: Accel read from IIO on 'iio:device0': 0, 0, 0 (scale 0.000010)
** (process:29051): DEBUG: 17:07:52.892: Accel sent by driver (quirk applied): 0, 0, 0 (scale: 0.000010)
** (process:29051): DEBUG: 17:07:53.593: No new data available on 'iio:device1'
** (process:29051): DEBUG: 17:07:53.593: process_scan_1: channel_index: 0, chan_name: in_accel_x, channel_data_index: 0 location: 0 bytes: 4 is_signed: 1 be: 0 shift: 0 bits_used: 32
** (process:29051): DEBUG: 17:07:53.593: process_scan_1: channel_index: 1, chan_name: in_accel_y, channel_data_index: 1 location: 4 bytes: 4 is_signed: 1 be: 0 shift: 0 bits_used: 32
** (process:29051): DEBUG: 17:07:53.593: process_scan_1: channel_index: 2, chan_name: in_accel_z, channel_data_index: 2 location: 8 bytes: 4 is_signed: 1 be: 0 shift: 0 bits_used: 32
** (process:29051): DEBUG: 17:07:53.594: Accel read from IIO on 'iio:device0': 0, 0, 0 (scale 0.000010)
** (process:29051): DEBUG: 17:07:53.594: Accel sent by driver (quirk applied): 0, 0, 0 (scale: 0.000010)
** (process:29051): DEBUG: 17:07:54.295: No new data available on 'iio:device1'
** (process:29051): DEBUG: 17:07:54.295: process_scan_1: channel_index: 0, chan_name: in_accel_x, channel_data_index: 0 location: 0 bytes: 4 is_signed: 1 be: 0 shift: 0 bits_used: 32
** (process:29051): DEBUG: 17:07:54.295: process_scan_1: channel_index: 1, chan_name: in_accel_y, channel_data_index: 1 location: 4 bytes: 4 is_signed: 1 be: 0 shift: 0 bits_used: 32
** (process:29051): DEBUG: 17:07:54.295: process_scan_1: channel_index: 2, chan_name: in_accel_z, channel_data_index: 2 location: 8 bytes: 4 is_signed: 1 be: 0 shift: 0 bits_used: 32
** (process:29051): DEBUG: 17:07:54.295: Accel read from IIO on 'iio:device0': 0, 0, 0 (scale 0.000010)
** (process:29051): DEBUG: 17:07:54.295: Accel sent by driver (quirk applied): 0, 0, 0 (scale: 0.000010)
** (process:29051): DEBUG: 17:07:54.996: No new data available on 'iio:device1'
** (process:29051): DEBUG: 17:07:54.996: process_scan_1: channel_index: 0, chan_name: in_accel_x, channel_data_index: 0 location: 0 bytes: 4 is_signed: 1 be: 0 shift: 0 bits_used: 32
** (process:29051): DEBUG: 17:07:54.996: process_scan_1: channel_index: 1, chan_name: in_accel_y, channel_data_index: 1 location: 4 bytes: 4 is_signed: 1 be: 0 shift: 0 bits_used: 32
** (process:29051): DEBUG: 17:07:54.996: process_scan_1: channel_index: 2, chan_name: in_accel_z, channel_data_index: 2 location: 8 bytes: 4 is_signed: 1 be: 0 shift: 0 bits_used: 32
** (process:29051): DEBUG: 17:07:54.996: Accel read from IIO on 'iio:device0': 0, 0, 0 (scale 0.000010)
** (process:29051): DEBUG: 17:07:54.996: Accel sent by driver (quirk applied): 0, 0, 0 (scale: 0.000010)`

**Comment by edhilgendorf** [comment] 2019-05-20 00:16
iio-sensor-proxy-2.6-1

**Comment by hadess** [comment] 2019-05-20 08:48
Duplicate of #270

**Closed by hadess** 2019-05-20 08:48 UTC
