### ISSUE TITLE
Not providing any sensible sensor values

### ISSUE THREAD

**Issue by seijikun** [hadess/iio-sensor-proxy#276] opened 2019-06-17 13:32 UTC
iio-sensor-proxy seems to at least properly detect accelerometer and ambient light sensors, but is unable to provide sensible values for them. (For example: ambient light always reports 0 Lux). Manually reading the raw sensor files in sysfs report proper values.

My System:
- OpenSUSE Tumbleweed
- Linux 5.1.7-1-default
- iio-sensor-proxy 2.6-1.3

KDE auto-rotate already worked once with this notebook, so this could be a regression.

monitor-sensors output:
```
    Waiting for iio-sensor-proxy to appear
+++ iio-sensor-proxy appeared
=== Has accelerometer (orientation: undefined)
=== Has ambient light sensor (value: 0.000000, unit: lux)
```

Here is the log of `iio-sensor-proxy` when run with debug-messages:
```
** (process:428): DEBUG: 15:19:40.418: Found IIO buffer ALS at /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200041.7.auto/iio:device2
** (process:428): DEBUG: 15:19:40.418: Found device /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200041.7.auto/iio:device2 of type ambient light sensor at IIO Buffer Light sensor
** (process:428): DEBUG: 15:19:40.421: Found associated trigger at /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/trigger4
** (process:428): DEBUG: 15:19:40.421: Found IIO buffer accelerometer at /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4
** (process:428): DEBUG: 15:19:40.421: No autodetected location, falling back to display location
** (process:428): DEBUG: 15:19:40.421: Found device /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4 of type accelerometer at IIO Buffer accelerometer
** (process:428): DEBUG: 15:19:40.421: Found IIO buffer compass at /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3
** (process:428): DEBUG: 15:19:40.421: Found device /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3 of type compass at IIO Buffer Compass
** (process:428): DEBUG: 15:19:40.423: Found associated trigger at /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/trigger4
** (process:428): DEBUG: 15:19:40.424: Already enabled sensor /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4/scan_elements/in_accel_x_en
** (process:428): DEBUG: 15:19:40.424: Already enabled sensor /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4/scan_elements/in_accel_z_en
** (process:428): DEBUG: 15:19:40.424: Already enabled sensor /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4/scan_elements/in_timestamp_en
** (process:428): DEBUG: 15:19:40.424: Already enabled sensor /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4/scan_elements/in_accel_y_en
** (process:428): DEBUG: 15:19:40.424: Trying to read 'in_accel_x_scale' (name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4'
** (process:428): DEBUG: 15:19:40.424: Failed to read float from /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4/in_accel_x_scale: No such file or directory
** (process:428): DEBUG: 15:19:40.424: Trying to read 'in_accel_scale' (generic name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4'
** (process:428): DEBUG: 15:19:40.424: Trying to read 'in_accel_x_offset' (name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4'
** (process:428): DEBUG: 15:19:40.424: Failed to read float from /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4/in_accel_x_offset: No such file or directory
** (process:428): DEBUG: 15:19:40.424: Trying to read 'in_accel_offset' (generic name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4'
** (process:428): DEBUG: 15:19:40.424: Got type for in_accel_x: is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:428): DEBUG: 15:19:40.424: Trying to read 'in_accel_z_scale' (name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4'
** (process:428): DEBUG: 15:19:40.424: Failed to read float from /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4/in_accel_z_scale: No such file or directory
** (process:428): DEBUG: 15:19:40.424: Trying to read 'in_accel_scale' (generic name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4'
** (process:428): DEBUG: 15:19:40.424: Trying to read 'in_accel_z_offset' (name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4'
** (process:428): DEBUG: 15:19:40.424: Failed to read float from /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4/in_accel_z_offset: No such file or directory
** (process:428): DEBUG: 15:19:40.424: Trying to read 'in_accel_offset' (generic name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4'
** (process:428): DEBUG: 15:19:40.424: Got type for in_accel_z: is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:428): DEBUG: 15:19:40.424: Trying to read 'in_timestamp_scale' (name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4'
** (process:428): DEBUG: 15:19:40.424: Failed to read float from /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4/in_timestamp_scale: No such file or directory
** (process:428): DEBUG: 15:19:40.424: Trying to read 'in_scale' (generic name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4'
** (process:428): DEBUG: 15:19:40.424: Failed to read float from /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4/in_scale: No such file or directory
** (process:428): DEBUG: 15:19:40.424: Trying to read 'in_timestamp_offset' (name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4'
** (process:428): DEBUG: 15:19:40.424: Failed to read float from /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4/in_timestamp_offset: No such file or directory
** (process:428): DEBUG: 15:19:40.424: Trying to read 'in_offset' (generic name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4'
** (process:428): DEBUG: 15:19:40.424: Failed to read float from /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4/in_offset: No such file or directory
** (process:428): DEBUG: 15:19:40.424: Got type for in_timestamp: is signed: 1, bytes: 8, bits_used: 64, shift: 0, mask: 0x18446744073709551615, be: 0
** (process:428): DEBUG: 15:19:40.424: Trying to read 'in_accel_y_scale' (name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4'
** (process:428): DEBUG: 15:19:40.424: Failed to read float from /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4/in_accel_y_scale: No such file or directory
** (process:428): DEBUG: 15:19:40.424: Trying to read 'in_accel_scale' (generic name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4'
** (process:428): DEBUG: 15:19:40.424: Trying to read 'in_accel_y_offset' (name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4'
** (process:428): DEBUG: 15:19:40.424: Failed to read float from /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4/in_accel_y_offset: No such file or directory
** (process:428): DEBUG: 15:19:40.425: Trying to read 'in_accel_offset' (generic name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4'
** (process:428): DEBUG: 15:19:40.425: Got type for in_accel_y: is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:428): DEBUG: 15:19:40.425: Built channel array for in_accel_x: index: 0, is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:428): DEBUG: 15:19:40.425: Built channel array for in_accel_y: index: 1, is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:428): DEBUG: 15:19:40.425: Built channel array for in_accel_z: index: 2, is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:428): DEBUG: 15:19:40.425: Built channel array for in_timestamp: index: 3, is signed: 1, bytes: 8, bits_used: 64, shift: 0, mask: 0x18446744073709551615, be: 0
** (process:428): DEBUG: 15:19:40.425: Failed to auto-detect mount matrix, falling back to identity
** (process:428): DEBUG: 15:19:40.425: No autodetected location, falling back to display location
** (process:428): DEBUG: 15:19:40.426: Found associated trigger at /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200041.7.auto/trigger1
** (process:428): DEBUG: 15:19:40.427: Already enabled sensor /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200041.7.auto/iio:device2/scan_elements/in_intensity_both_en
** (process:428): DEBUG: 15:19:40.427: Already enabled sensor /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200041.7.auto/iio:device2/scan_elements/in_illuminance_en
** (process:428): DEBUG: 15:19:40.427: Trying to read 'in_intensity_both_scale' (name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200041.7.auto/iio:device2'
** (process:428): DEBUG: 15:19:40.427: Failed to read float from /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200041.7.auto/iio:device2/in_intensity_both_scale: No such file or directory
** (process:428): DEBUG: 15:19:40.427: Trying to read 'in_intensity_scale' (generic name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200041.7.auto/iio:device2'
** (process:428): DEBUG: 15:19:40.427: Trying to read 'in_intensity_both_offset' (name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200041.7.auto/iio:device2'
** (process:428): DEBUG: 15:19:40.427: Failed to read float from /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200041.7.auto/iio:device2/in_intensity_both_offset: No such file or directory
** (process:428): DEBUG: 15:19:40.427: Trying to read 'in_intensity_offset' (generic name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200041.7.auto/iio:device2'
** (process:428): DEBUG: 15:19:40.427: Got type for in_intensity_both: is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:428): DEBUG: 15:19:40.427: Trying to read 'in_illuminance_scale' (name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200041.7.auto/iio:device2'
** (process:428): DEBUG: 15:19:40.427: Trying to read 'in_illuminance_offset' (name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200041.7.auto/iio:device2'
** (process:428): DEBUG: 15:19:40.427: Got type for in_illuminance: is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:428): DEBUG: 15:19:40.427: Built channel array for in_intensity_both: index: 0, is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:428): DEBUG: 15:19:40.427: Built channel array for in_illuminance: index: 1, is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:428): DEBUG: 15:19:40.430: Found associated trigger at /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/trigger3
** (process:428): DEBUG: 15:19:40.431: Already enabled sensor /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3/scan_elements/in_magn_z_en
** (process:428): DEBUG: 15:19:40.431: Already enabled sensor /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3/scan_elements/in_magn_y_en
** (process:428): DEBUG: 15:19:40.431: Already enabled sensor /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3/scan_elements/in_magn_x_en
** (process:428): DEBUG: 15:19:40.431: Already enabled sensor /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3/scan_elements/in_rot_from_north_magnetic_tilt_comp_en
** (process:428): DEBUG: 15:19:40.431: Trying to read 'in_magn_z_scale' (name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3'
** (process:428): DEBUG: 15:19:40.431: Failed to read float from /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3/in_magn_z_scale: No such file or directory
** (process:428): DEBUG: 15:19:40.431: Trying to read 'in_magn_scale' (generic name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3'
** (process:428): DEBUG: 15:19:40.431: Trying to read 'in_magn_z_offset' (name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3'
** (process:428): DEBUG: 15:19:40.431: Failed to read float from /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3/in_magn_z_offset: No such file or directory
** (process:428): DEBUG: 15:19:40.431: Trying to read 'in_magn_offset' (generic name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3'
** (process:428): DEBUG: 15:19:40.431: Got type for in_magn_z: is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:428): DEBUG: 15:19:40.432: Trying to read 'in_magn_y_scale' (name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3'
** (process:428): DEBUG: 15:19:40.432: Failed to read float from /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3/in_magn_y_scale: No such file or directory
** (process:428): DEBUG: 15:19:40.432: Trying to read 'in_magn_scale' (generic name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3'
** (process:428): DEBUG: 15:19:40.432: Trying to read 'in_magn_y_offset' (name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3'
** (process:428): DEBUG: 15:19:40.432: Failed to read float from /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3/in_magn_y_offset: No such file or directory
** (process:428): DEBUG: 15:19:40.432: Trying to read 'in_magn_offset' (generic name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3'
** (process:428): DEBUG: 15:19:40.432: Got type for in_magn_y: is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:428): DEBUG: 15:19:40.432: Trying to read 'in_magn_x_scale' (name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3'
** (process:428): DEBUG: 15:19:40.432: Failed to read float from /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3/in_magn_x_scale: No such file or directory
** (process:428): DEBUG: 15:19:40.432: Trying to read 'in_magn_scale' (generic name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3'
** (process:428): DEBUG: 15:19:40.432: Trying to read 'in_magn_x_offset' (name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3'
** (process:428): DEBUG: 15:19:40.432: Failed to read float from /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3/in_magn_x_offset: No such file or directory
** (process:428): DEBUG: 15:19:40.432: Trying to read 'in_magn_offset' (generic name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3'
** (process:428): DEBUG: 15:19:40.432: Got type for in_magn_x: is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:428): DEBUG: 15:19:40.432: Trying to read 'in_rot_from_north_magnetic_tilt_comp_scale' (name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3'
** (process:428): DEBUG: 15:19:40.432: Failed to read float from /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3/in_rot_from_north_magnetic_tilt_comp_scale: No such file or directory
** (process:428): DEBUG: 15:19:40.432: Trying to read 'in_rot_scale' (generic name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3'
** (process:428): DEBUG: 15:19:40.432: Trying to read 'in_rot_from_north_magnetic_tilt_comp_offset' (name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3'
** (process:428): DEBUG: 15:19:40.432: Failed to read float from /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3/in_rot_from_north_magnetic_tilt_comp_offset: No such file or directory
** (process:428): DEBUG: 15:19:40.432: Trying to read 'in_rot_offset' (generic name) from dir '/sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3'
** (process:428): DEBUG: 15:19:40.432: Got type for in_rot_from_north_magnetic_tilt_comp: is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:428): DEBUG: 15:19:40.432: Built channel array for in_magn_x: index: 0, is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:428): DEBUG: 15:19:40.432: Built channel array for in_magn_y: index: 1, is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:428): DEBUG: 15:19:40.432: Built channel array for in_magn_z: index: 2, is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
** (process:428): DEBUG: 15:19:40.432: Built channel array for in_rot_from_north_magnetic_tilt_comp: index: 3, is signed: 1, bytes: 4, bits_used: 32, shift: 0, mask: 0x0, be: 0
```

Here is the sysfs structure:
```
.
├── iio:device0 -> ../../../devices/LNXSYSTM:00/LNXSYBUS:00/TOS6208:00/iio:device0
│   ├── dev
│   ├── name
│   ├── out_accel_x_raw
│   ├── out_accel_y_raw
│   ├── out_accel_z_raw
│   ├── power
│   ├── subsystem -> ../../../../../bus/iio
│   └── uevent
├── iio:device1 -> ../../../devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-20008a.6.auto/iio:device1
│   ├── buffer
│   ├── dev
│   ├── in_rot_hysteresis
│   ├── in_rot_offset
│   ├── in_rot_quaternion_raw
│   ├── in_rot_sampling_frequency
│   ├── in_rot_scale
│   ├── name
│   ├── power
│   ├── scan_elements
│   ├── subsystem -> ../../../../../../../../../bus/iio  [recursive, not followed]
│   ├── trigger
│   └── uevent
├── iio:device2 -> ../../../devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200041.7.auto/iio:device2
│   ├── buffer
│   ├── dev
│   ├── in_illuminance_hysteresis
│   ├── in_illuminance_offset
│   ├── in_illuminance_raw
│   ├── in_illuminance_sampling_frequency
│   ├── in_illuminance_scale
│   ├── in_intensity_both_raw
│   ├── in_intensity_hysteresis
│   ├── in_intensity_offset
│   ├── in_intensity_sampling_frequency
│   ├── in_intensity_scale
│   ├── name
│   ├── power
│   ├── scan_elements
│   ├── subsystem -> ../../../../../../../../../bus/iio  [recursive, not followed]
│   ├── trigger
│   └── uevent
├── iio:device3 -> ../../../devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/iio:device3
│   ├── buffer
│   ├── dev
│   ├── in_magn_hysteresis
│   ├── in_magn_offset
│   ├── in_magn_sampling_frequency
│   ├── in_magn_scale
│   ├── in_magn_x_raw
│   ├── in_magn_y_raw
│   ├── in_magn_z_raw
│   ├── in_rot_from_north_magnetic_tilt_comp_raw
│   ├── in_rot_hysteresis
│   ├── in_rot_offset
│   ├── in_rot_sampling_frequency
│   ├── in_rot_scale
│   ├── name
│   ├── power
│   ├── scan_elements
│   ├── subsystem -> ../../../../../../../../../bus/iio  [recursive, not followed]
│   ├── trigger
│   └── uevent
├── iio:device4 -> ../../../devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/iio:device4
│   ├── buffer
│   ├── current_timestamp_clock
│   ├── dev
│   ├── in_accel_hysteresis
│   ├── in_accel_offset
│   ├── in_accel_sampling_frequency
│   ├── in_accel_scale
│   ├── in_accel_x_raw
│   ├── in_accel_y_raw
│   ├── in_accel_z_raw
│   ├── name
│   ├── power
│   ├── scan_elements
│   ├── subsystem -> ../../../../../../../../../bus/iio  [recursive, not followed]
│   ├── trigger
│   └── uevent
├── iio:device5 -> ../../../devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200086.5.auto/iio:device5
│   ├── buffer
│   ├── dev
│   ├── in_incli_hysteresis
│   ├── in_incli_offset
│   ├── in_incli_sampling_frequency
│   ├── in_incli_scale
│   ├── in_incli_x_raw
│   ├── in_incli_y_raw
│   ├── in_incli_z_raw
│   ├── name
│   ├── power
│   ├── scan_elements
│   ├── subsystem -> ../../../../../../../../../bus/iio  [recursive, not followed]
│   ├── trigger
│   └── uevent
├── iio:device6 -> ../../../devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200076.3.auto/iio:device6
│   ├── buffer
│   ├── dev
│   ├── in_anglvel_hysteresis
│   ├── in_anglvel_offset
│   ├── in_anglvel_sampling_frequency
│   ├── in_anglvel_scale
│   ├── in_anglvel_x_raw
│   ├── in_anglvel_y_raw
│   ├── in_anglvel_z_raw
│   ├── name
│   ├── power
│   ├── scan_elements
│   ├── subsystem -> ../../../../../../../../../bus/iio  [recursive, not followed]
│   ├── trigger
│   └── uevent
├── trigger0 -> ../../../devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-20008a.6.auto/trigger0
│   ├── name
│   ├── power
│   ├── subsystem -> ../../../../../../../../../bus/iio  [recursive, not followed]
│   └── uevent
├── trigger1 -> ../../../devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200041.7.auto/trigger1
│   ├── name
│   ├── power
│   ├── subsystem -> ../../../../../../../../../bus/iio  [recursive, not followed]
│   └── uevent
├── trigger2 -> ../../../devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200076.3.auto/trigger2
│   ├── name
│   ├── power
│   ├── subsystem -> ../../../../../../../../../bus/iio  [recursive, not followed]
│   └── uevent
├── trigger3 -> ../../../devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200083.4.auto/trigger3
│   ├── name
│   ├── power
│   ├── subsystem -> ../../../../../../../../../bus/iio  [recursive, not followed]
│   └── uevent
├── trigger4 -> ../../../devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200073.2.auto/trigger4
│   ├── name
│   ├── power
│   ├── subsystem -> ../../../../../../../../../bus/iio  [recursive, not followed]
│   └── uevent
└── trigger5 -> ../../../devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/0003:0483:91D1.0001/HID-SENSOR-200086.5.auto/trigger5
    ├── name
    ├── power
    ├── subsystem -> ../../../../../../../../../bus/iio  [recursive, not followed]
    └── uevent
```

**Comment by hadess** [comment] 2019-06-17 14:05
Duplicate of #270

Please make sure to test the latest released versions in the future, thanks.

**Closed by hadess** 2019-06-17 14:05 UTC
